### ISSUE TITLE
News add error

### ISSUE THREAD

**Issue by Demonith** [paintballrefjosh/MaNGOSWebV4#30] opened 2017-03-27 09:23 UTC
When add news to the site via Admin Panel i get this in front page

Couldnt Run Query: SELECT username FROM account WHERE id = '1'
Error: Table 'wowsite.account' doesn't exist

Also when add in db its working but the name who posted not changing its always Mistvale.com Dev Team

**Comment by Cubansephiroth** [comment] 2017-03-27 15:01
Cant reproduce your issue i can post news fine from the admin panel and news author is my current logged admin user not the Mistvale.com Dev Team. My mangosweb tables are inside my auth DB (Trinity based core) that account table your error is showing is the account table of your auth DB.

**Comment by paintballrefjosh** [comment] 2017-03-27 18:41
Demonith is probably on the latest release which rewrote a lot of the core of this project.  I have committed a fix for the news error.  It also addresses a couple other issues related to the commands page.  Here are the files you'll want to update:

inc/server/server.commands.php - [View Here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/6800ccac2db7b0aef0b90bca46b555cad3301e5e/inc/server/server.commands.php)
templates/blizzlike/server/server.commands.php - [View Here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/6800ccac2db7b0aef0b90bca46b555cad3301e5e/templates/blizzlike/server/server.commands.php)
templates/blizzlike/frontpage/frontpage.index.php - [View Here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/6800ccac2db7b0aef0b90bca46b555cad3301e5e/templates/blizzlike/frontpage/frontpage.index.php)

I've also updated the release zip with the fixes which you can grab [at this link](https://github.com/paintballrefjosh/MaNGOSWebV4/releases/tag/4.1.0)

This should resolve the news issue, if not please let me know.

**Comment by Cubansephiroth** [comment] 2017-03-27 20:23
As of 6800ccac2db7b0aef0b90bca46b555cad3301e5e news system is working fine.

**Comment by paintballrefjosh** [comment] 2017-03-27 21:12
Great, thanks for checking @Cubansephiroth.

**Closed as completed by paintballrefjosh** 2017-03-27 21:12 UTC
Labels: bug

**Comment by Demonith** [comment] 2017-03-27 22:31
Yep this fixed the problem tnx
